services:
  app:
    image: health-tracker:local
    container_name: health-tracker
    restart: unless-stopped

    build:
      context: /srv/repos/health-tracker
      dockerfile: Dockerfile

    command: ["uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8000"]

    # Persisted app data (db later) + backups folder (even if host-run)
    volumes:
      - /srv/compose/health-tracker/data:/data
      - /srv/compose/health-tracker/backups:/backups

      # Option B: bind-mount repo for fast iteration
      - /srv/repos/health-tracker:/app

    environment:
      - TZ=America/Chicago

    networks:
      - proxy

    labels:
      - traefik.enable=true
      - traefik.http.routers.health-tracker.rule=Host(`health.home.cniebuhr.com`)
      - traefik.http.routers.health-tracker.entrypoints=websecure
      - traefik.http.routers.health-tracker.tls=true
      - traefik.http.services.health-tracker.loadbalancer.server.port=8000

networks:
  proxy:
    external: true